### ISSUE TITLE
Incorrect handling of trailing zeros in comparisons

### ISSUE THREAD

**Issue by njsmith** [relrod/pep440-rs#2]
Quoth PEP 440:

> X.Y and X.Y.0 are not considered distinct release numbers, as the release segment comparison rules implicit expand the two component form to X.Y.0 when comparing it to any release segment that includes three components.

Unfortunately, this code acts differently:

```rust
use pep440::Version;

fn main() {
    let v1 = Version::parse("1.0").unwrap();
    let v2 = Version::parse("1.0.0").unwrap();

    println!("{}", v1 == v2);   // false  (should be true)
    println!("{}", v1 != v2);   // true   (should be false)
    println!("{}", v1 < v2);    // false  (correct)
    println!("{}", v1 <= v2);   // true   (correct)
    println!("{}", v1 > v2);    // false  (correct)
    println!("{}", v1 >= v2);   // true   (correct)
}
```

Note that this doesn't even define a consistent ordering -- the two versions are `<=` and `>=`, which should imply that they're `==`... but they aren't.

I also noticed that `normalize()` doesn't convert these into the same form... which I think might actually be correct? I'm only like 90% sure. But it does mean that I can't use `normalize()` to implement a version of `Hash` that agrees with `Eq`, so now I'm not sure how to make versions hashable.

**Comment by Eh2406** [comment]
Note that this brakes one of the requirements of the Ord trait 
> total and asymmetric: exactly one of `a < b`, `a == b` or `a > b` is true

but
```rs
    println!("{}", v1 == v2);   // false  (should be true)
    println!("{}", v1 < v2);    // false  (correct)
    println!("{}", v1 > v2);    // false  (correct)
```
